### ISSUE TITLE
Test Posts Don't Send At Scheduled Time

### ISSUE THREAD

**Issue by TCC-UK** [medartus/feedmyflow#6]
I think the title sums it up. I tried various solutions, hard reload, clearing cache, incognito windows, but nothing worked. 

Took a quick look in dev tools, 
<img width="1394" alt="Screen Shot 2020-05-30 at 9 55 08 PM" src="https://user-images.githubusercontent.com/59293208/83344899-dab67580-a2c1-11ea-857b-8457f040dc5c.png">

**Desktop (please complete the following information):**
 - OS: 	Mac OS 10.15.5
 - Browser: Chrome 
 - Version	83.0.4103.61

<img width="766" alt="Screen Shot 2020-05-30 at 8 29 14 PM" src="https://user-images.githubusercontent.com/59293208/83344662-cfae1600-a2be-11ea-8368-531168c7a6ec.png">
<img width="766" alt="Screen Shot 2020-05-30 at 8 31 24 PM" src="https://user-images.githubusercontent.com/59293208/83344673-f2402f00-a2be-11ea-8402-38e28edea881.png">
<img width="766" alt="Screen Shot 2020-05-30 at 9 05 58 PM" src="https://user-images.githubusercontent.com/59293208/83344679-0552ff00-a2bf-11ea-979b-4199cd52c50a.png">

**Additional context**
I really want this to work, because having closed my FB, TW, and Medium  accounts, this is all I need. SimonG

**Comment by medartus** [comment]
Hi Simon,
Don't worry about searching in the frontend, the scheduling task is handle in the backend. The issue was that the scheduling server was down.
I change the server to be more reliable and to always be up.

I also find some issue with the content creation, I fix the issue at the same time.

I schedule your post for next week for you to reschedule it when you want!
Marc-Etienne Dartus

**Comment by TCC-UK** [comment]
Awesome, Marc-Etienne,  thank you for the fix. Looking forward to using FMF and telling my friends and network about it.

**Comment by TCC-UK** [comment]
FYI worked perfectly. Thanks again.
